### ISSUE TITLE
Correções do documento do minimundo

### ISSUE THREAD

**Issue by pedroirineu5** [fukczun/my-game-list#40]
Realizar as seguintes correções no documento do minimundo:
- Corrigir multivalorado do status;
- Delimitar a cardinalidade dos relacionamentos;
- Renomear relacionamento "**dentro**" para "**Vinculado**";
- Quebrar 2 colunas na própria ListaJogo, caso os atributos serão: {nome do jogo, nota e comentário};

**Comment by IagoMoreira26** [comment]
Praticamente feito, restou somente alguns detalhes que deixarei para a próxima reunião.
